# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d95daa22eaff9e2aa603a6dfe72ade6f"
application_url = "https://contain-better-thrown-ensemble.trycloudflare.com"
embedded = true
name = "3D Model Viewer"
handle = "webgpu-3d-viewer-1"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "webgpu.myshopify.com"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_product_listings"

[auth]
redirect_urls = [
  "https://contain-better-thrown-ensemble.trycloudflare.com/auth/callback",
  "https://contain-better-thrown-ensemble.trycloudflare.com/auth/shopify/callback",
  "https://contain-better-thrown-ensemble.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
